# Generated by Django 3.0.6 on 2020-08-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0003_auto_20200819_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Целевые',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Номер_участка', models.CharField(max_length=100)),
                ('Сумма_долга', models.CharField(max_length=100)),
                ('Счетчик', models.CharField(default='No issues', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Членские',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Номер_участка', models.CharField(max_length=100)),
                ('Сумма_долга', models.CharField(max_length=100)),
                ('Счетчик', models.CharField(default='No issues', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Электроэнергия',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Номер_участка', models.CharField(max_length=100)),
                ('Сумма_долга', models.CharField(max_length=100)),
                ('Счетчик', models.CharField(default='No issues', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
