# Generated by Django 3.0.6 on 2020-08-21 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0004_целевые_членские_электроэнергия'),
    ]

    operations = [
        migrations.RenameField(
            model_name='целевые',
            old_name='Номер_участка',
            new_name='Адрес',
        ),
        migrations.RenameField(
            model_name='целевые',
            old_name='Счетчик',
            new_name='Задолженность',
        ),
        migrations.RenameField(
            model_name='целевые',
            old_name='Сумма_долга',
            new_name='ФИО',
        ),
        migrations.RenameField(
            model_name='членские',
            old_name='Номер_участка',
            new_name='Адрес',
        ),
        migrations.RenameField(
            model_name='членские',
            old_name='Счетчик',
            new_name='Задолженность',
        ),
        migrations.RenameField(
            model_name='членские',
            old_name='Сумма_долга',
            new_name='ФИО',
        ),
        migrations.RenameField(
            model_name='электроэнергия',
            old_name='Номер_участка',
            new_name='Адрес',
        ),
        migrations.RenameField(
            model_name='электроэнергия',
            old_name='Счетчик',
            new_name='Задолженность',
        ),
        migrations.RenameField(
            model_name='электроэнергия',
            old_name='Сумма_долга',
            new_name='ФИО',
        ),
        migrations.AddField(
            model_name='целевые',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='членские',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='электроэнергия',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
