# Generated by Django 3.0.6 on 2020-08-25 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0005_auto_20200821_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='ДоскаПозора',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(default='', max_length=250)),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo1', models.ImageField(blank='True', null='True', upload_to='media_shame', verbose_name='Изображение1')),
                ('photo2', models.ImageField(blank='True', null='True', upload_to='media_shame', verbose_name='Изображение2')),
                ('photo3', models.ImageField(blank='True', null='True', upload_to='media_shame', verbose_name='Изображение3')),
            ],
        ),
        migrations.DeleteModel(
            name='Base',
        ),
        migrations.DeleteModel(
            name='MainPage',
        ),
    ]
