# Generated by Django 3.0.6 on 2020-08-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0006_auto_20200825_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Протоколы_Собраний',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(default='', max_length=250)),
                ('document', models.FileField(blank='True', default='', null='True', upload_to='documentation/')),
            ],
        ),
    ]
