# Generated by Django 3.0.6 on 2020-08-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0007_протоколы_собраний'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='document',
            field=models.FileField(blank='True', default='', null='True', upload_to='media/'),
        ),
    ]
