# Generated by Django 3.0.6 on 2020-08-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0010_auto_20200825_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleinside',
            name='document',
            field=models.ImageField(blank='True', default='', null='True', upload_to='documentation/'),
        ),
    ]
