# Generated by Django 3.0.6 on 2020-09-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0013_auto_20200903_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='главная',
            name='document',
            field=models.FileField(blank='True', null='True', upload_to='media_community/', verbose_name='Файл'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='главная',
            name='image2',
            field=models.ImageField(blank='True', null='True', upload_to='media_community/', verbose_name='Изображение'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='главная',
            name='image3',
            field=models.ImageField(blank='True', null='True', upload_to='media_community/', verbose_name='Изображение'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='главная',
            name='image4',
            field=models.ImageField(blank='True', null='True', upload_to='media_community/', verbose_name='Изображение'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='главная',
            name='image5',
            field=models.ImageField(blank='True', null='True', upload_to='media_community/', verbose_name='Изображение'),
            preserve_default='True',
        ),
    ]
