# Generated by Django 3.0.6 on 2020-09-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0015_протоколы_собраний_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='АдминистрацияСТ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(default='', max_length=250)),
                ('Должность', models.TextField(max_length=250)),
                ('ФИО', models.TextField(max_length=250)),
                ('Номер_телефона', models.TextField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Правление',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(default='', max_length=250)),
                ('Должность', models.TextField(max_length=250)),
                ('ФИО', models.TextField(max_length=250)),
                ('Номер_телефона', models.TextField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='РевизионнаяКомиссия',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(default='', max_length=250)),
                ('Должность', models.TextField(max_length=250)),
                ('ФИО', models.TextField(max_length=250)),
                ('Номер_телефона', models.TextField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='СчетнаяКомиссия',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(default='', max_length=250)),
                ('Должность', models.TextField(max_length=250)),
                ('ФИО', models.TextField(max_length=250)),
                ('Номер_телефона', models.TextField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Уполномоченные',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(default='', max_length=250)),
                ('Должность', models.TextField(max_length=250)),
                ('ФИО', models.TextField(max_length=250)),
                ('Номер_телефона', models.TextField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Администрация',
        ),
    ]
